<?xml version="1.0" encoding="UTF-8"?>
<ROOT>
     <HEADER>
     
     </HEADER>
     <BODY>
         <request>
            <brNo>${brNo!}</brNo>
            <batNo>${batNo!}</batNo>
            <dataCnt>${dataCnt!}</dataCnt>
            <pactNo>${pactNo!}</pactNo>
            <custName>${custName!}</custName>
            <idType>${idType!}</idType>
            <idNo>${idNo!}</idNo>
            <custType>${custType!}</custType>
            <sex>${sex!}</sex>
            <birth>${birth!}</birth>
            <marriage>${marriage!}</marriage>
            <children>${children!}</children>
            <edu>${edu!}</edu>
            <degree>${degree!}</degree>
            <telNo>${telNo!}</telNo>
            <phoneNo>${phoneNo!}</phoneNo>
            <postCode>${postCode!}</postCode>
            <postAddr>${postAddr!}</postAddr>
            <homeArea>${homeArea!}</homeArea>
            <homeTel>${homeTel!}</homeTel>
            <homeCode>${homeCode!}</homeCode>
            <homeAddr>${homeAddr!}</homeAddr>
            <homeSts>${homeSts!}</homeSts>
            <income>${income!}</income>
            <mateName>${mateName!}</mateName>
            <mateIdtype>${mateIdtype!}</mateIdtype>
            <mateIdno>${mateIdno!}</mateIdno>
            <mateWork>${mateWork!}</mateWork>
            <mateTel>${mateTel!}</mateTel>
            <projNo>${projNo!}</projNo>
            <prdtNo>${prdtNo!}</prdtNo>
            <pactAmt>${pactAmt!}</pactAmt>
            <feeTotal>${feeTotal!}</feeTotal>
            <premNo>${premNo!}</premNo>
            <premRate>${premRate!}</premRate>
            <lnRate>${lnRate!}</lnRate>
            <appArea>${appArea!}</appArea>
            <appUse>${appUse!}</appUse>
            <termMon>${termMon!}</termMon>
            <termDay>${termDay!}</termDay>
            <vouType>${vouType!}</vouType>
            <endDate>${endDate!}</endDate>
            <payType>${payType!}</payType>
            <payDay>${payDay!}</payDay>
            <vouAmt>${vouAmt!}</vouAmt>
            <acUse>${acUse!}</acUse>
            <acAmt>${acAmt!}</acAmt>
            <acType>${acType!}</acType>
            <acno>${acno!}</acno>
            <acName>${acName!}</acName>
            <bankCode>${bankCode!}</bankCode>
            <bankProv>${bankProv!}</bankProv>
            <bankCity>${bankCity!}</bankCity>
            <bankSite>${bankSite!}</bankSite>
            <idType>${idType!}</idType>
            <idNo>${idNo!}</idNo>
            <phoneNo>${phoneNo!}</phoneNo>
            <validDate>${validDate!}</validDate>
            <cvvNo>${cvvNo!}</cvvNo>
            <gcustName>${gcustName!}</gcustName>
            <gcustIdtype>${gcustIdtype!}</gcustIdtype>
            <gcustIdno>${gcustIdno!}</gcustIdno>
            <gType>${gType!}</gType>
            <gName>${gName!}</gName>
            <gDesc>${gDesc!}</gDesc>
            <gValue>${gValue!}</gValue>
            <gLicno>${gLicno!}</gLicno>
            <gLicType>${gLicType!}</gLicType>
            <gBegBal>${gBegBal!}</gBegBal>
            <gSmType>${gSmType!}</gSmType>
            <gWorkType>${gWorkType!}</gWorkType>
            <workType>${workType!}</workType>
            <workName>${workName!}</workName>
            <workWay>${workWay!}</workWay>
            <workCode>${workCode!}</workCode>
            <workAddr>${workAddr!}</workAddr>
            <workDuty>${workDuty!}</workDuty>
            <workTitle>${workTitle!}</workTitle>
            <workYear>${workYear!}</workYear>
            <comName>${comName!}</comName>
            <comIdtype>${comIdtype!}</comIdtype>
            <comIdno>${comIdno!}</comIdno>
            <comTel>${comTel!}</comTel>
            <relName>${relName!}</relName>
            <relIdtype>${relIdtype!}</relIdtype>
            <relIdno>${relIdno!}</relIdno>
            <relTel>${relTel!}</relTel>
            <ifCar>${ifCar!}</ifCar>
            <ifCarCred>${ifCarCred!}</ifCarCred>
            <ifRoom>${ifRoom!}</ifRoom>
            <ifMort>${ifMort!}</ifMort>
            <ifCard>${ifCard!}</ifCard>
            <cardAmt>${cardAmt!}</cardAmt>
            <ifApp>${ifApp!}</ifApp>
            <ifId>${ifId!}</ifId>
            <ifPact>${ifPact!}</ifPact>
            <prePactNo>${prePactNo!}</prePactNo>
            <czPactNo>${czPactNo!}</czPactNo>
            <workSts>${workSts!}</workSts>
            <cardChn>${cardChn!}</cardChn>
         </request>
     </BODY>
</ROOT>