<?xml version="1.0" encoding="GBK"?>
<conditions>
	<condition queryType="10102">
		<item>
			<name>unitName</name>
			<value>${unitName!''}</value>
		</item>
		<item>
			<name>organUnitName</name>
			<value>${organUnitName!''}</value>
		</item>
		<item>
			<name>bankName</name>
			<value>${bankName!''}</value>
		</item>
		<item>
			<name>pgsqId</name>			
			<value>${serialId!''}</value>
		</item>
		<item>
			<name>buyPrice</name>			
			<value>${dealAmount!''}</value>
		</item>
		<item>
			<name>limitPrice</name>			
			<value>${loanAmount!''}</value>
		</item>
		<item>
			<name>content</name>
			<value>${content!''}</value>
		</item>
	</condition>
</conditions>