
package com.anjbo.app;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.util.ResourceUtils;

import com.anjbo.creditapp.InfWsLoginService;
import com.anjbo.ws.InfWsProcessService;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InfWsSearchService", targetNamespace = "http://ws.inf.creditapp.app/", wsdlLocation = "http://183.238.238.164:9000/cms/services/searchService?wsdl")
public class InfWsSearchService extends Service {

	private final static URL INFWSSEARCHSERVICE_WSDL_LOCATION;
	private final static WebServiceException INFWSSEARCHSERVICE_EXCEPTION;
	private final static QName INFWSSEARCHSERVICE_QNAME = new QName("http://ws.inf.creditapp.app/",
			"InfWsSearchService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = InfWsProcessService.class.getResource("/sgtws/stgSearchService.wsdl");
			if (url == null) {
				url = ResourceUtils.getURL(ResourceUtils.CLASSPATH_URL_PREFIX + "/sgtws/stgSearchService.wsdl");
			}
			System.out.println("url=======" + url);
		} catch (Exception ex) {
			e = new WebServiceException(ex);
		}
		INFWSSEARCHSERVICE_WSDL_LOCATION = url;
		INFWSSEARCHSERVICE_EXCEPTION = e;
	}

	public InfWsSearchService() {
		super(__getWsdlLocation(), INFWSSEARCHSERVICE_QNAME);
	}

	public InfWsSearchService(WebServiceFeature... features) {
		super(__getWsdlLocation(), INFWSSEARCHSERVICE_QNAME, features);
	}

	public InfWsSearchService(URL wsdlLocation) {
		super(wsdlLocation, INFWSSEARCHSERVICE_QNAME);
	}

	public InfWsSearchService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, INFWSSEARCHSERVICE_QNAME, features);
	}

	public InfWsSearchService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public InfWsSearchService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns InfWsSearch
	 */
	@WebEndpoint(name = "InfWsSearchPort")
	public InfWsSearch getInfWsSearchPort() {
		return super.getPort(new QName("http://ws.inf.creditapp.app/", "InfWsSearchPort"), InfWsSearch.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on
	 *            the proxy. Supported features not in the <code>features</code>
	 *            parameter will have their default values.
	 * @return returns InfWsSearch
	 */
	@WebEndpoint(name = "InfWsSearchPort")
	public InfWsSearch getInfWsSearchPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://ws.inf.creditapp.app/", "InfWsSearchPort"), InfWsSearch.class, features);
	}

	private static URL __getWsdlLocation() {
		if (INFWSSEARCHSERVICE_EXCEPTION != null) {
			throw INFWSSEARCHSERVICE_EXCEPTION;
		}
		return INFWSSEARCHSERVICE_WSDL_LOCATION;
	}

}
