
package com.anjbo.ws.ccb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgencyCompanyServer", targetNamespace = "http://agency.impl.server.webservice.grape.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgencyCompanyServer {


    /**
     * 中介公司交易入口,tranCode为交易号，encryptFlag为是否加密[0-否，1-是],context为报文内容
     * 
     * @param encryptFlag
     * @param tranCode
     * @param context
     * @return
     *     returns com.grape.webservice.server.impl.agency.SecondHouseLoadResp
     */
    @WebMethod
    @WebResult(name = "secondHouseLoadReqResult", targetNamespace = "")
    @RequestWrapper(localName = "agencyCompanyLoadReq", targetNamespace = "http://agency.impl.server.webservice.grape.com/", className = "com.anjbo.ws.ccb.AgencyCompanyLoadReq")
    @ResponseWrapper(localName = "agencyCompanyLoadReqResponse", targetNamespace = "http://agency.impl.server.webservice.grape.com/", className = "com.anjbo.ws.ccb.AgencyCompanyLoadReqResponse")
    public SecondHouseLoadResp agencyCompanyLoadReq(
            @WebParam(name = "tranCode", targetNamespace = "")
                    String tranCode,
            @WebParam(name = "encryptFlag", targetNamespace = "")
                    int encryptFlag,
            @WebParam(name = "context", targetNamespace = "")
                    String context);

}
