<?xml version="1.0" encoding="UTF-8"?>
<ROOT>
	<HEADER>
		<TRANNO>${tranNo!}</TRANNO>
		<COMNO>${comNo!}</COMNO>
		<BNKNO>${bankNo!}</BNKNO>
		<CHANNELNO>${channelNo!}</CHANNELNO>
		<ISN>${isn!}</ISN>
	</HEADER>
	<BODY>
		<BASEINFO>
			<APPNO>${appNo!}</APPNO>
			<RSRVTN_DT>${reserveDate!}</RSRVTN_DT>
			<RSRVTN_TM>${reserveTime!}</RSRVTN_TM>
			<HLD_PLC_DSC>${reserveAddress!}</HLD_PLC_DSC>
			<EXEC_RSLT_DSC>${remark!}</EXEC_RSLT_DSC>
		</BASEINFO>
	</BODY>
</ROOT>