
package com.anjbo.ws.ccb;

import com.anjbo.common.Constants;
import com.anjbo.common.ThirdApiConstants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "agencyCompanyServer", targetNamespace = "http://agency.impl.server.webservice.grape.com/", wsdlLocation = "http://192.168.1.15:7003/agencyCompany?wsdl")
public class AgencyCompanyServer_Service
    extends Service
{

    private final static URL AGENCYCOMPANYSERVER_WSDL_LOCATION;
    private final static WebServiceException AGENCYCOMPANYSERVER_EXCEPTION;
    private final static QName AGENCYCOMPANYSERVER_QNAME = new QName("http://agency.impl.server.webservice.grape.com/", "agencyCompanyServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(ThirdApiConstants.CCB_WS_URL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCYCOMPANYSERVER_WSDL_LOCATION = url;
        AGENCYCOMPANYSERVER_EXCEPTION = e;
    }

    public AgencyCompanyServer_Service() {
        super(__getWsdlLocation(), AGENCYCOMPANYSERVER_QNAME);
    }

    public AgencyCompanyServer_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCYCOMPANYSERVER_QNAME, features);
    }

    public AgencyCompanyServer_Service(URL wsdlLocation) {
        super(wsdlLocation, AGENCYCOMPANYSERVER_QNAME);
    }

    public AgencyCompanyServer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCYCOMPANYSERVER_QNAME, features);
    }

    public AgencyCompanyServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgencyCompanyServer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgencyCompanyServer
     */
    @WebEndpoint(name = "AgencyCompanyServerPort")
    public AgencyCompanyServer getAgencyCompanyServerPort() {
        return super.getPort(new QName("http://agency.impl.server.webservice.grape.com/", "AgencyCompanyServerPort"), AgencyCompanyServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgencyCompanyServer
     */
    @WebEndpoint(name = "AgencyCompanyServerPort")
    public AgencyCompanyServer getAgencyCompanyServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://agency.impl.server.webservice.grape.com/", "AgencyCompanyServerPort"), AgencyCompanyServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCYCOMPANYSERVER_EXCEPTION!= null) {
            throw AGENCYCOMPANYSERVER_EXCEPTION;
        }
        return AGENCYCOMPANYSERVER_WSDL_LOCATION;
    }

}
