<?xml version="1.0" encoding="GBK"?>
<xml>
   <appid>${appid!''}</appid>
   <mch_id>${mch_id!''}</mch_id>
   <device_info>${device_info!''}</device_info>
   <nonce_str>${nonce_str!''}</nonce_str>
   <sign>${sign!''}</sign>
   <body>${body!''}</body>
   <out_trade_no>${out_trade_no!''}</out_trade_no>
   <total_fee>${total_fee!''}</total_fee>
   <spbill_create_ip>${spbill_create_ip!''}</spbill_create_ip>
   <time_start>${time_start!''}</time_start>
   <time_expire>${time_expire!''}</time_expire>
   <notify_url>${notify_url!''}</notify_url>
   <trade_type>${trade_type!''}</trade_type>
   <openid>${openid!''}</openid>
   <transaction_id>${transaction_id!''}</transaction_id>
   <attach>${attach!''}</attach>
</xml>