<#setting number_format="#0.00">
<?xml version="1.0" encoding="UTF-8"?>
<ROOT>
	<HEADER>
		<TRANNO>${tranNo!}</TRANNO>
		<COMNO>${comNo!}</COMNO>
		<BNKNO>${bankNo!}</BNKNO>
		<CHANNELNO>${channelNo!}</CHANNELNO>
		<ISN>${isn!}</ISN>
	</HEADER>
	<BODY>
		<CUSINFO>
			<Cst_Nm>${name!}</Cst_Nm>
			<Crdt_TpCd>${certificateType!}</Crdt_TpCd>
			<Crdt_No>${certificateNo!}</Crdt_No>
			<Gnd_Cd>${sex!}</Gnd_Cd>
			<Brth_Dt>${dateBirth!}</Brth_Dt>
			<Mar_Sttn_Cd>${marital!}</Mar_Sttn_Cd>
			<EdDgr_Cd>${education!}</EdDgr_Cd>
			<IdCst_Lcl_Rsdnc_Tm>${localLiveTime!}</IdCst_Lcl_Rsdnc_Tm>
			<Email_Adr>${email!}</Email_Adr>
			<Dtl_Adr>${currAddress!}</Dtl_Adr>
			<ZipECD>${zipCode!}</ZipECD>
			<Ctc_Tel>${familyPhone!}</Ctc_Tel>
			<Fam_Ppn_Num>${familySize!}</Fam_Ppn_Num>
			<Move_TelNo>${mobile!}</Move_TelNo>
			<Tot_Co_Nm>${workUnit!}</Tot_Co_Nm>
			<Wrk_TelNo>${unitPhone!}</Wrk_TelNo>
			<Idv_Mo_IncmAm>${personIncome!}</Idv_Mo_IncmAm>
			<Prov_AtnmsRgon_Cd>440000</Prov_AtnmsRgon_Cd>
			<Urbn_AtnmsDstc_Cd>440300</Urbn_AtnmsDstc_Cd>
			<CntyAndDstc_Cd>440305</CntyAndDstc_Cd>
			<RspbPsn_Phone>${jhphone!}</RspbPsn_Phone>
			<Nat_Cd>156</Nat_Cd>
			<Ethnct_Cd>${nation!}</Ethnct_Cd>
			<Rsdnc_Sttn_Cd>${live!}</Rsdnc_Sttn_Cd>
			<Fam_Mo_IncmAm>${familyIncome!}</Fam_Mo_IncmAm>
			<Expn_Amt>${familyExpend!}</Expn_Amt>
			<Fam_Tot_Ast_Amt>${familyAssets!}</Fam_Tot_Ast_Amt>
			<Fam_Tot_Lby_Amt>${familyLiabilities!}</Fam_Tot_Lby_Amt>
			<EcIst_RpyAmt>${personPayments!}</EcIst_RpyAmt>
			<Chl_Sttn_Cd>${children!}</Chl_Sttn_Cd>
			<Wrk_Exprnc_StDt>${unitTime!}</Wrk_Exprnc_StDt>
			<Main_Ecn_SrcCd>${mainSources!}</Main_Ecn_SrcCd>
			<HshldRgst_Adr>${censusReg!}</HshldRgst_Adr>
			<Parn_RspbPsn_ID>${agentName!}</Parn_RspbPsn_ID>
			<Parn_RspbPsn_Phone>${agentMobile!}</Parn_RspbPsn_Phone>
		</CUSINFO>
	</BODY>
</ROOT>